### ISSUE TITLE
Add spdlog

### ISSUE THREAD

**Issue by rafaelxero** [rafaelxero/jrlutil#21]
For mc_rtc to be able to compile, we need to add

```
sudo apt install libspdlog-dev
```

Because it now depends on spdlog

**Comment by arntanguy** [comment]
Sorry, actually we install it from source.

```
sudo apt remove libspdlog-dev
git clone -b v1.6.1 https://github.com/gabime/spdlog.git
mkdir -p spdlog/build
cd spdlog/build
cmake -DCMAKE_BUILD_TYPE=Release -DSPDLOG_BUILD_EXAMPLE:BOOL=OFF -DSPDLOG_BUILD_SHARED:BOOL=ON ..
make
sudo make install
```

Should do the trick

**Comment by rafaelxero** [comment]
It has to be in v1.6.1
If it is in master then mc_rtc complains

**Comment by mehdi-benallegue** [comment]
Sorry the last sentence was not clear. So I tried to do something but I did not test it. 

I will prepare the PR as soon as the current one is merged.

**Comment by mehdi-benallegue** [comment]
I think that if you know what should be done to fix the installation, you can maybe do it more easily than me. Because I am
1. trying to understand the problem
2. copying the code that you already wrote
3. making the modification without being sure that it works
4. committing, pushing and PR
5. waiting for the PR to be merged.

If you had to do it, you can just
1.  copy the code that you wrote already (with some modifications that I have to do anyways)
2.  then commit and push.
