### ISSUE TITLE
Running install.sh multiple times

### ISSUE THREAD

**Issue by rafaelxero** [rafaelxero/jrlutil#6]
If for some reason it is required to re-run the install.sh script it will give several fatal errors because some directories already exist. It is better not only to check if the directory exists or not, but if the corresponding git repository is there or not (maybe the user erased the contents of the directory, but not the directory itself)

**Comment by Nbot07** [comment]
If the folder is still a git repository, then the user could checkout any files that are missing. Therefore this use case seems too unlikely and irrelevant, to me, to warrant implementing this check. However, since in this situation the user is already deleting files, if you still want this to be implemented, would it not be more effective to update the README by stating that the user should delete any directories that they want re-cloned before re-running install.sh? I ask because a user deleting a folder, then re-running install.sh and a user deleting files from a folder then re-running install.sh seem equivalent to me. Specifically, if files are deleted from the folder, then the files would need to be downloaded again anyway for the folder, that was originally generated by cloning a repo, to be useful.

**Comment by rafaelxero** [comment]
Ok, I agree. Let's just update the README in the way that you said.

**Comment by Nbot07** [comment]
https://github.com/rafaelxero/jrlutil/commit/e726e774e2aade5ad48f3aef2f0a1a215cec020b
